/// Flutter icons TurbochargerIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TurbochargerIcons
///      fonts:
///       - asset: fonts/TurbochargerIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TurbochargerIcons {
  TurbochargerIcons._();

  static const _kFontFam = 'TurbochargerIcons';

  static const IconData iconturbo2048px =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData iconcylinder2048px =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData iconenginecalc2048px =
      const IconData(0xe802, fontFamily: _kFontFam);
}
